name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
        
    - name: yarn install
      run: |
        cd node
        yarn install
    - name: docker build
      run: |
        docker build -t temp/build
