name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
        
    - name: yarn install
      run: |
        cd node
        yarn install
    - name: docker build
      run: |
        docker build -t temp/build ./node
    -name: docker login
     run: |
       docker login -u "henbx" -p "password" docker.io
       docker push henbx/excell-pipe:0.0.1
    - name: Push docker image
      run: |
        docker tag temp/build henbx/excell-pipe:latest
        docker tag temp/build henbx/excell-pipe:${{ github.sha }}
        docker push henbx/excell-pipe:latest
        docker push henbx/excell-pipe:${{ github.sha }}
