---
name: Build Docker Image

on:
  push:
    branches: 
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    name: Test Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Testing
        run: |
          cd node
          yarn install
          yarn test
