---
name: Build Docker Image

on: push

runs-on: ubuntu-latest

jobs:
  deploy:
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo Continue here...
