---
name: Build Docker Image

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: yarn test
      run: |
        yarn test
      env:
        CI: true
